/* Account administration is a separate operator-only surface and native command. */
(()=>{
 const button=node('button','button ghost','管理');button.id='operator-open';button.type='button';button.hidden=true;document.querySelector('.top-actions').append(button);
 const dialog=node('dialog','operator-dialog');dialog.id='operator-dialog';
 dialog.innerHTML=`<header class="operator-heading"><div><p class="eyebrow">OPERATOR</p><h2>管理</h2></div><button id="operator-close" class="button subtle" type="button">关闭</button></header>
 <nav class="operator-tabs" aria-label="管理类别"><button data-tab="users" class="button primary">用户</button><button data-tab="games" class="button subtle">对局</button><button data-tab="invitations" class="button subtle">邀请码</button></nav>
 <p id="operator-status" role="status"></p>
 <section id="operator-users"><div class="operator-tools"><input id="operator-user-query" type="search" placeholder="搜索用户名" aria-label="搜索用户名"><button id="operator-user-search" class="button subtle">搜索</button></div>
 <div class="operator-tools"><button id="operator-disable" class="button subtle">禁止登录</button><button id="operator-enable" class="button subtle">恢复登录</button><button id="operator-delete-users" class="button danger">删除用户</button><span id="operator-user-selected"></span></div>
 <p class="small muted">删除账号保留历史对局与署名。禁止登录和重置密码会立即撤销原登录会话。</p><div class="operator-table"><table><thead><tr><th><input id="operator-users-all" type="checkbox" aria-label="选择本页用户"></th><th>用户名</th><th>身份</th><th>状态</th><th>操作</th></tr></thead><tbody id="operator-users-body"></tbody></table></div>
 <div class="operator-tools"><button id="operator-users-prev" class="button subtle">上一页</button><span id="operator-users-page"></span><button id="operator-users-next" class="button subtle">下一页</button></div></section>
 <section id="operator-games" hidden><div class="operator-tools"><select id="operator-game-status" aria-label="对局状态"><option value="">全部对局</option><option value="active">进行中</option><option value="completed">已完成</option><option value="truncated">已中止</option></select><button id="operator-games-refresh" class="button subtle">刷新</button></div>
 <div class="operator-tools"><button id="operator-stop" class="button subtle">中止所选对局</button><button id="operator-delete-games" class="button danger">删除所选数据</button><span id="operator-game-selected"></span></div>
 <p class="small muted">只能删除已结束对局。删除会永久移除该局轨迹、消息、附件及关联房间。</p><div class="operator-table"><table><thead><tr><th><input id="operator-games-all" type="checkbox" aria-label="选择本页对局"></th><th>对局</th><th>状态</th><th>分数</th><th>人数</th><th>参赛成员</th><th>结束原因</th><th>创建时间</th><th></th></tr></thead><tbody id="operator-games-body"></tbody></table></div>
 <div class="operator-tools"><button id="operator-games-prev" class="button subtle">上一页</button><span id="operator-games-page"></span><button id="operator-games-next" class="button subtle">下一页</button></div></section>
 <section id="operator-invitations" hidden><form id="operator-invite-form"><div class="operator-tools"><label>数量<input id="operator-invite-count" type="number" min="1" max="100" value="1" required></label><label>有效天数<input id="operator-invite-days" type="number" min="1" max="365" value="30" required></label><button class="button primary" type="submit">生成邀请码</button></div></form><p class="small muted">每码只能注册一个普通账号。请逐个私下发放，关闭管理页后清空本页清单。</p><textarea id="operator-invite-result" readonly rows="9" aria-label="生成的邀请码"></textarea><button id="operator-copy-invites" class="button subtle" disabled>复制清单</button></section>`;
 document.body.append(dialog);
 const confirm=node('dialog','operator-confirm');confirm.innerHTML='<h3 id="operator-confirm-title"></h3><p id="operator-confirm-detail"></p><label id="operator-password-label" hidden>新密码<input id="operator-password" type="password" autocomplete="new-password" minlength="12" maxlength="128"></label><div class="operator-tools"><button id="operator-confirm-cancel" class="button subtle">取消</button><button id="operator-confirm-yes" class="button danger">确认</button></div>';document.body.append(confirm);
 let tab='users',epoch=0,busy=false,userOffset=0,gameOffset=0,userTotal=0,gameTotal=0,userRows=[],gameRows=[],confirmResolve,pending;
 const selectedUsers=new Set(),selectedGames=new Set(),selectedGameDetails=new Map();
 const status=(text,error=false)=>{setText('operator-status',text);$('operator-status').className=error?'notice error':'small muted';};
 const allowed=()=>Boolean(state.token&&state.identity?.role==='operator');
 const pageSize=25;
 function selection(){setText('operator-user-selected',`已选 ${selectedUsers.size} 人`);setText('operator-game-selected',`已选 ${selectedGames.size} 局`);for(const id of ['operator-disable','operator-enable','operator-delete-users'])$(id).disabled=busy||!selectedUsers.size;for(const id of ['operator-stop','operator-delete-games'])$(id).disabled=busy||!selectedGames.size;}
 function refreshVisibility(){button.hidden=!allowed();if(!allowed())clear();}
 function clear(){epoch++;selectedUsers.clear();selectedGames.clear();selectedGameDetails.clear();userRows=[];gameRows=[];pending=null;busy=false;button.hidden=true;$('operator-invite-result').value='';$('operator-password').value='';$('operator-copy-invites').disabled=true;for(const id of ['operator-users-body','operator-games-body'])$(id).replaceChildren();if(dialog.open)dialog.close();if(confirm.open)confirm.close();confirmResolve?.(null);confirmResolve=null;}
 function ask(title,detail,password=false){setText('operator-confirm-title',title);setText('operator-confirm-detail',detail);$('operator-password-label').hidden=!password;$('operator-password').value='';confirm.showModal();if(password)$('operator-password').focus();return new Promise(resolve=>{confirmResolve=resolve;});}
 const dismiss=value=>{const resolve=confirmResolve;confirmResolve=null;$('operator-password').value='';confirm.close();resolve?.(value);};
 $('operator-confirm-cancel').onclick=()=>dismiss(null);confirm.addEventListener('cancel',event=>{event.preventDefault();dismiss(null);});
 $('operator-confirm-yes').onclick=()=>{const value=$('operator-password-label').hidden?true:$('operator-password').value;if(typeof value==='string'&&(Array.from(value).length<12||Array.from(value).length>128||!value.trim())){$('operator-password').setCustomValidity('请输入 12–128 个字符的新密码。');$('operator-password').reportValidity();return;}$('operator-password').setCustomValidity('');dismiss(value);};
 function checkbox(id,selected,disabled=false,onChange){const input=node('input');input.type='checkbox';input.checked=selected.has(id);input.disabled=disabled;input.setAttribute('aria-label','选择 '+id);input.onchange=()=>{if(input.checked&&selected.size>=100){input.checked=false;status('每次最多选择 100 条记录。',true);return;}if(input.checked)selected.add(id);else selected.delete(id);onChange?.(input.checked);selection();};return input;}
 function cell(row,content,label){const td=node('td');if(label)td.dataset.label=label;if(typeof content==='string')td.textContent=content;else td.append(content);row.append(td);}
 const score=game=>Number.isFinite(game.outcome?.score)?`${game.outcome.score}${Number.isFinite(game.outcome?.maxScore)?'/'+game.outcome.maxScore:''}`:game.status==='active'?'进行中':game.status==='truncated'?'未结算':'未记录';
 const members=game=>(game.participants??[]).map(p=>`${p.playerId} · ${p.name||'姓名未记录'}${p.accountId&&p.accountId!==p.name?'（账号 '+p.accountId+'）':''}`).join('、')||'成员未记录';
 const ending=game=>game.status==='active'?'进行中':game.status==='completed'?game.outcome?.reason||'按规则结束':game.endReason||'中止原因未记录';
 async function loadUsers(){const serial=epoch,data=await request(`/operator/users?limit=${pageSize}&offset=${userOffset}&q=${encodeURIComponent($('operator-user-query').value.trim())}`);if(serial!==epoch||!allowed())return;userRows=data.users;userTotal=data.total;const body=$('operator-users-body');body.replaceChildren();for(const user of userRows){const row=node('tr');cell(row,checkbox(user.id,selectedUsers,user.id===state.identity.id));cell(row,user.id);cell(row,user.role==='operator'?'管理员':'普通用户');cell(row,user.disabled?'禁止登录':'正常');const reset=node('button','button subtle','重置密码');reset.disabled=user.id===state.identity.id;reset.onclick=()=>void act(async()=>{const password=await ask(`重置 ${user.id} 的密码`,'旧密码和全部旧登录会话会立即失效。请输入新密码。',true);if(password===null)return;await mutate('users/reset-password',{userId:user.id,password});});cell(row,reset);body.append(row);}setText('operator-users-page',`共 ${userTotal} 人 · 第 ${Math.floor(userOffset/pageSize)+1} 页`);$('operator-users-prev').disabled=userOffset===0;$('operator-users-next').disabled=userOffset+pageSize>=userTotal;$('operator-users-all').checked=false;selection();}
 async function loadGames(){const serial=epoch,data=await request(`/operator/games?limit=${pageSize}&offset=${gameOffset}${$('operator-game-status').value?'&status='+$('operator-game-status').value:''}`);if(serial!==epoch||!allowed())return;gameRows=data.items;gameTotal=data.total;const body=$('operator-games-body');body.replaceChildren();for(const game of gameRows){const row=node('tr');cell(row,checkbox(game.episodeId,selectedGames,false,checked=>{if(checked)selectedGameDetails.set(game.episodeId,game);else selectedGameDetails.delete(game.episodeId);}));cell(row,game.name||game.gameName||game.gameId);cell(row,({active:'进行中',completed:'已完成',truncated:'已中止'})[game.status]||game.status);cell(row,score(game),'分数');cell(row,String(game.playerCount??game.participants?.length??'—'),'人数');cell(row,members(game),'成员');cell(row,ending(game),'结束');cell(row,date(game.createdAt),'创建');const replay=node('button','button subtle','回放');replay.onclick=()=>{dialog.close();void selectEpisode(game.episodeId).catch(e=>message(e.message,true));};cell(row,replay);body.append(row);if(selectedGames.has(game.episodeId))selectedGameDetails.set(game.episodeId,game);}setText('operator-games-page',`共 ${gameTotal} 局 · 第 ${Math.floor(gameOffset/pageSize)+1} 页`);$('operator-games-prev').disabled=gameOffset===0;$('operator-games-next').disabled=gameOffset+pageSize>=gameTotal;$('operator-games-all').checked=false;selection();}
 async function act(work){if(busy||!allowed())return;const serial=epoch;busy=true;selection();try{await work();}catch(error){if(serial===epoch){const messages={ACTIVE_GAME:'所选对局仍有进行中的游戏，请先单独中止。',FORBIDDEN:'没有权限，或不能操作自己的管理员账号。',NOT_FOUND:'部分记录已不存在，请刷新列表。',INVALID_REQUEST:'输入不符合要求，请检查数量、有效期和密码。',RATE_LIMITED:'操作过于频繁，请稍后重试。'};status(messages[error.code]??(error.code==='CANCELLED'?'登录已改变，请重新打开管理页面。':'操作未完成。若网络中断，重新点击同一操作会沿用请求编号重试。'),true);}}finally{if(serial===epoch){busy=false;selection();}}}
 async function mutate(operation,payload){const serial=epoch,fingerprint=JSON.stringify({operation,payload});if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,requestId:crypto.randomUUID()};const result=await transport.operatorCommand({operation,body:{...payload,requestId:pending.requestId}});if(serial!==epoch||!allowed())return null;pending=null;status('操作完成。');return result;}
 async function userAction(operation){const ids=[...selectedUsers];if(!ids.length)return;const labels={disable:'禁止登录',enable:'恢复登录',delete:'删除账号'};if(await ask(`${labels[operation]}：${ids.length} 个用户`,`${ids.join('、')}。${operation==='delete'?'账号及密码将移除，历史对局与署名保留；已删除用户名不会重新分配。':'此操作不改动历史对局。'}`)===null)return;const result=await mutate('users/'+operation,{userIds:ids,...(operation==='delete'?{confirm:true}:{})});if(result){selectedUsers.clear();await loadUsers();}}
 for(const [id,operation]of [['operator-disable','disable'],['operator-enable','enable'],['operator-delete-users','delete']])$(id).onclick=()=>void act(()=>userAction(operation));
 async function gameAction(operation){const ids=[...selectedGames];if(!ids.length)return;const summary=ids.map(id=>{const game=selectedGameDetails.get(id);return game?`${game.name||game.gameName||game.gameId} · ${score(game)}${Number.isFinite(game.outcome?.score)?' 分':''} · ${game.playerCount} 人 · ${members(game)} · ${ending(game)}`:`${id} · 请刷新后核对`;}).join('\n');if(await ask(`${operation==='delete'?'永久删除':'中止'} ${ids.length} 局`,`${summary}\n\n${operation==='delete'?'只能删除已结束对局。轨迹、消息、附件及关联房间将永久移除，无法从客户端恢复。':'所选进行中的对局将立即中止，已有轨迹和附件保留。'}`)===null)return;const result=await mutate('games/'+operation,{episodeIds:ids,...(operation==='delete'?{confirm:true}:{reason:'管理员手动中止'})});if(result){selectedGames.clear();selectedGameDetails.clear();await loadGames();await loadList();void window.CoopLobby?.refresh();}}
 $('operator-stop').onclick=()=>void act(()=>gameAction('stop'));$('operator-delete-games').onclick=()=>void act(()=>gameAction('delete'));
 $('operator-invite-form').onsubmit=event=>{event.preventDefault();void act(async()=>{const result=await mutate('invitations',{count:Number($('operator-invite-count').value),expiresInDays:Number($('operator-invite-days').value)});if(!result)return;$('operator-invite-result').value=result.invitations.map((value,i)=>`${i+1}. ${value.code}\n有效至：${date(value.expiresAt,true)}`).join('\n\n');$('operator-copy-invites').disabled=false;status(`已生成 ${result.invitations.length} 个一次性邀请码。`);});};
 $('operator-copy-invites').onclick=()=>void act(async()=>{await transport.copyText($('operator-invite-result').value);status('邀请码清单已复制。');});
 for(const kind of ['users','games'])$('operator-'+kind+'-all').onchange=()=>{const selected=kind==='users'?selectedUsers:selectedGames,rows=kind==='users'?userRows:gameRows,checked=$('operator-'+kind+'-all').checked;for(const row of rows){const id=kind==='users'?row.id:row.episodeId;if(kind==='users'&&id===state.identity.id)continue;if(checked&&selected.size<100){selected.add(id);if(kind==='games')selectedGameDetails.set(id,row);}else if(!checked){selected.delete(id);if(kind==='games')selectedGameDetails.delete(id);}}void act(kind==='users'?loadUsers:loadGames);};
 $('operator-user-search').onclick=()=>void act(async()=>{userOffset=0;selectedUsers.clear();await loadUsers();});$('operator-games-refresh').onclick=()=>void act(loadGames);$('operator-game-status').onchange=()=>void act(async()=>{gameOffset=0;selectedGames.clear();selectedGameDetails.clear();await loadGames();});
 for(const [kind,direction]of [['users','prev'],['users','next'],['games','prev'],['games','next']])$('operator-'+kind+'-'+direction).onclick=()=>void act(async()=>{const delta=direction==='next'?pageSize:-pageSize;if(kind==='users'){userOffset=Math.max(0,userOffset+delta);await loadUsers();}else{gameOffset=Math.max(0,gameOffset+delta);await loadGames();}});
 for(const control of dialog.querySelectorAll('[data-tab]'))control.onclick=()=>void act(async()=>{tab=control.dataset.tab;for(const other of dialog.querySelectorAll('[data-tab]'))other.className='button '+(other===control?'primary':'subtle');for(const name of ['users','games','invitations'])$('operator-'+name).hidden=name!==tab;status('');if(tab==='users'){userRows=[];$('operator-users-body').replaceChildren();await loadUsers();}if(tab==='games'){gameRows=[];$('operator-games-body').replaceChildren();await loadGames();}});
 button.onclick=()=>{if(!allowed())return;dialog.showModal();void act(tab==='users'?loadUsers:tab==='games'?loadGames:async()=>{});};
 $('operator-close').onclick=()=>{if(busy)return;clear();refreshVisibility();};dialog.addEventListener('cancel',event=>{event.preventDefault();if(!busy){clear();refreshVisibility();}});
 window.CoopOperator=Object.freeze({clear,refreshVisibility});refreshVisibility();
})();
