import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {writeFileSync,readFileSync} from 'node:fs';
import {app,safeStorage} from 'electron';
import {join} from 'node:path';
import {setTimeout as wait} from 'node:timers/promises';
import {startMockApi} from './mock-api.mjs';
import {inviteUrl} from '../runtime/coop-bench/client/player.mjs';

export async function runPlayerSmoke({window,directory}) {
  const local=await startMockApi(),checks=[];
  const js=code=>window.webContents.executeJavaScript(code).catch(error=>{throw Error(`Player UI script failed: ${code.slice(0,500)}`,{cause:error});});
  const until=async code=>{for(let i=0;i<160;i++){if(await js(code))return;await wait(100);}throw Error('Player UI condition failed: '+code);};
  const call=async(path,token=local.adminToken,body)=>{
    const res=await fetch(local.apiUrl+path,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
    const data=await res.json();assert.ok(res.ok,JSON.stringify(data));return data;
  };
  try{
    await until("document.querySelector('#status').textContent==='尚未连接'");checks.push('visible startup and disconnected status');
    assert.equal(await js("document.querySelector('#resume').disabled"),true);checks.push('fresh profile does not offer unavailable seat recovery');
    const room=await call('/rooms',undefined,{gameId:'hanabi',scenarioId:'base',playerCount:2}),url=inviteUrl({...room,apiUrl:local.apiUrl});
    app.emit('open-url',{preventDefault(){}},'coopbench://join#invalid');assert.equal(await js("document.querySelector('#invitation').value"),'');
    app.emit('open-url',{preventDefault(){}},url);await until("document.querySelector('#invitation').value.startsWith('coopbench://join#')");
    assert.equal(await js("document.querySelector('#lobby').hidden"),true);checks.push('validated invitation deep link prefills without silently joining');
    await js("document.querySelector('#name').value='Synthetic human';document.querySelector('#join-form').requestSubmit();");
    await until("!document.querySelector('#lobby').hidden");checks.push('invitation joins human UI');
    if(safeStorage.isEncryptionAvailable()){
      await call(`/rooms/${room.roomId}/admin-invite`,undefined,{});
      await js("window.coopPlayer.command('disconnect').then(render)");
      await js("document.querySelector('#mode').value='model';document.querySelector('#mode').dispatchEvent(new Event('change'));document.querySelector('#base-url').value='https://synthetic-model.example/v1';document.querySelector('#model').value='synthetic-model';document.querySelector('#api-key').value='synthetic-api-key';document.querySelector('#resume').click()");
      await until("!document.querySelector('#lobby').hidden && document.querySelector('#session-mode').textContent==='模型 API 自动参赛'");
      assert.equal(await js("document.querySelector('#api-key').value"),'');
      const persisted=JSON.parse(safeStorage.decryptString(readFileSync(join(directory,'membership.encrypted'))));
      assert.equal(persisted.inviteToken,undefined);assert.equal(persisted.apiKey,undefined);checks.push('model seat resumes after invite rotation with no persisted invite or model key');
      await js("window.coopPlayer.command('disconnect').then(render)");
      await js("document.querySelector('#mode').value='human';document.querySelector('#mode').dispatchEvent(new Event('change'));document.querySelector('#resume').click()");
      await until("!document.querySelector('#lobby').hidden && document.querySelector('#session-mode').textContent==='人类玩家'");
    }else checks.push('native encrypted seat recovery unavailable on this host; resume test skipped');
    // The earlier invitation has been rotated by the recovery test.
    const activeInvite=await call(`/rooms/${room.roomId}/admin-invite`,undefined,{});
    const peer=randomBytes(32).toString('base64url');await call(`/rooms/${room.roomId}/join`,activeInvite.inviteToken,{name:'Synthetic peer',playerToken:peer});
    await until("document.querySelectorAll('.member').length===2");await js("document.querySelector('#ready').click()");
    const roster=await call(`/rooms/${room.roomId}`,peer);await call(`/rooms/${room.roomId}/ready`,peer,{ready:true,rosterVersion:roster.rosterVersion});
    await until("!document.querySelector('#start').disabled");await js("document.querySelector('#start').click()");await until("!document.querySelector('#game').hidden");checks.push('roster readiness and host start');
    const snapshot=await js("window.coopPlayer.command('status')");assert.equal(snapshot.observation.playerId,'p1');assert.equal(snapshot.observation.decisionToken,undefined);assert.ok(snapshot.observation.view.hands.p1.every(c=>c.value===undefined));checks.push('renderer receives only projected own seat, no decision credentials');
    assert.equal(await js("document.querySelectorAll('.hint-counter .token-dot.filled').length"),8);assert.equal(await js("document.querySelectorAll('.hint-counter .token-dot').length"),8);assert.match(await js("document.querySelector('#deadline').textContent"),/秒/);assert.match(await js("document.querySelector('#deadline').textContent"),/\d{2}:\d{2}/);assert.match(await js("document.querySelector('#timeout-policy').textContent"),/超时后自动执行默认合法动作/);checks.push('filled and hollow hint counters, countdown and automatic timeout action visible');
    await js("document.querySelector('#rules-button').click()");assert.match(await js("document.querySelector('#rules-content').textContent"),/hint/i);await js("document.querySelector('#close-rules').click()");checks.push('read game rules');
    assert.deepEqual(await js("[...document.querySelector('[name=value]').options].map(o=>o.textContent)"),['红','蓝','绿','黄','白']);
    await js("document.querySelector('[name=kind]').value='\"value\"';document.querySelector('[name=kind]').dispatchEvent(new Event('change'))");
    assert.deepEqual(await js("[...document.querySelector('[name=value]').options].map(o=>JSON.parse(o.value))"),[1,2,3,4,5]);
    assert.match(await js("document.querySelector('[name=value]').parentElement.textContent"),/^提示数字/);
    await js("document.querySelector('[name=value]').value='5';document.querySelector('[name=kind]').value='\"color\"';document.querySelector('[name=kind]').dispatchEvent(new Event('change'))");
    assert.deepEqual(await js("[...document.querySelector('[name=value]').options].map(o=>o.textContent)"),['红','蓝','绿','黄','白']);
    assert.equal(await js("document.querySelector('[name=value]').value"),'"red"');checks.push('hint type switches between only colors and only numbers and resets an incompatible value');
    assert.equal(await js("document.querySelector('#manual-actions').open"),false);
    const beforeActions=local.requests.filter(r=>r.path.endsWith('/actions')).length;
    await js("document.querySelector('.card[data-player=p1][data-index=\"4\"]').click();document.querySelector('[data-choice=play]').click()");
    assert.equal(await js("document.querySelector('.card.card-preview').dataset.index"),'4');
    assert.match(await js("document.querySelector('#card-action-preview').textContent"),/第 5 张/);
    assert.equal(local.requests.filter(r=>r.path.endsWith('/actions')).length,beforeActions);
    await js("document.querySelector('#confirm-card-action').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
    assert.equal(await js("document.querySelector('#card-action-panel')"),null);
    checks.push('clicking own card and choosing play previews without submission; Escape cancels');
    await js("document.querySelector('.card[data-player=p2][data-index=\"0\"]').click();document.querySelector('[data-choice=color]').click()");
    assert.deepEqual(await js("[...document.querySelectorAll('.card.card-preview')].map(c=>c.dataset.index)"),['0','2']);
    assert.equal(await js("document.querySelectorAll('.card.hint-excluded').length"),3);
    await js("document.querySelector('#card-action-panel').scrollIntoView({block:'nearest'})");await wait(200);
    writeFileSync(join(directory,'player-hint-color-preview.png'),(await window.webContents.capturePage()).toPNG());
    await js("document.querySelector('[data-choice=value]').click()");
    assert.deepEqual(await js("[...document.querySelectorAll('.card.card-preview')].map(c=>c.dataset.index)"),['0','4']);
    assert.match(await js("document.querySelector('#card-action-preview').textContent"),/数字 2/);
    assert.equal(local.requests.filter(r=>r.path.endsWith('/actions')).length,beforeActions);
    await js("document.querySelector('.card[data-player=p2][data-index=\"3\"]').click()");
    assert.equal(await js("document.querySelector('#confirm-card-action').disabled"),true);
    assert.equal(await js("document.querySelectorAll('.card.card-preview').length"),0);
    await js("document.querySelector('.card[data-player=p2][data-index=\"0\"]').click();document.querySelector('[data-choice=color]').click();document.querySelector('#confirm-card-action').click();document.querySelector('#confirm-card-action')?.click()");
    await until("document.querySelectorAll('.hint-counter .token-dot.filled').length===7");checks.push('human action accepted and board updated via runtime');
    assert.equal(local.requests.filter(r=>r.path.endsWith('/actions')).length,beforeActions+1);
    assert.equal(await js("document.querySelector('#card-action-panel')"),null);
    checks.push('hint preview highlights all matching colors or numbers; changing cards resets the choice and confirmation submits exactly once');
    assert.match(await js("document.querySelectorAll('.player-hand')[1].textContent"),/牌主知道/);
    assert.equal(await js("document.querySelectorAll('.player-hand')[1].querySelector('.card-knowledge').textContent"),'牌主知道红1–5');
    assert.match(await js("document.querySelectorAll('.player-hand')[1].querySelectorAll('.card-knowledge')[1].textContent"),/非红/);
    checks.push('teammate positive and negative hint knowledge appears separately from visible card faces');
    await until("document.querySelector('#action-history').textContent.includes('命中第 1、3 张牌')");
    const beforeReload=await js("document.querySelector('#action-history').textContent");
    await new Promise(resolve=>{window.webContents.once('did-finish-load',resolve);window.webContents.reload();});await until("document.querySelector('#action-history').textContent.includes('命中第 1、3 张牌')");
    assert.equal(await js("document.querySelector('#action-history').textContent"),beforeReload);
    assert.equal(await js("document.querySelectorAll('#action-history li').length"),1);
    checks.push('readable history survives renderer reload without duplicate actions');
    await wait(300);
    writeFileSync(join(directory,'player-hanabi.png'),(await window.webContents.capturePage()).toPNG());
    await js("document.querySelector('#manual-actions').open=true;document.querySelector('[name=kind]').value='\"value\"';document.querySelector('[name=kind]').dispatchEvent(new Event('change'));document.querySelector('[name=value]').value='5';document.querySelector('#action-form').requestSubmit()");
    await until("!document.querySelector('#act').disabled");assert.deepEqual(local.requests.filter(r=>r.path.endsWith('/actions')).at(-1).body.action,{type:'hint',target:'p2',kind:'value',value:5});checks.push('number hints submit a numeric value');
    await js("document.querySelector('#action-type').value='play';document.querySelector('#action-type').dispatchEvent(new Event('change'))");
    assert.deepEqual(await js("[...document.querySelector('[name=index]').options].map(o=>o.textContent)"),[1,2,3,4,5].map(i=>`第 ${i} 张牌`));
    await js("document.querySelector('.card[data-player=p1][data-index=\"4\"]').click();document.querySelector('[data-choice=play]').click();document.querySelector('#confirm-card-action').click()");await until("!document.querySelector('#act').disabled");
    assert.deepEqual(local.requests.filter(r=>r.path.endsWith('/actions')).at(-1).body.action,{type:'play',index:4});
    await js("document.querySelector('#action-type').value='discard';document.querySelector('#action-type').dispatchEvent(new Event('change'))");
    assert.deepEqual(await js("(()=>{const input=document.querySelector('[name=index]');return [input.min,input.max,input.value]})()"),['1','5','1']);
    await js("document.querySelector('.card[data-player=p1][data-index=\"4\"]').click();document.querySelector('[data-choice=discard]').click();document.querySelector('#confirm-card-action').click()");await until("!document.querySelector('#act').disabled");
    assert.deepEqual(local.requests.filter(r=>r.path.endsWith('/actions')).at(-1).body.action,{type:'discard',index:4});checks.push('enum and numeric card positions display 1–5 and submit the fifth card with protocol index 4');
    await js("document.querySelector('.card[data-player=p1][data-index=\"0\"]').click();document.querySelector('[data-choice=play]').click()");
    await js("window.coopPlayer.command('status').then(s=>render({...s,clockOffsetMs:200000}))");
    assert.equal(await js("document.querySelector('#confirm-card-action').disabled"),true);
    await js("window.coopPlayer.command('status').then(render)");
    await call(`/episodes/${snapshot.room.episodeId}/truncate`,undefined,{reason:'synthetic-player-ui-test'});
    await until("document.querySelector('#status').textContent==='游戏结束'");checks.push('server terminal observation wakes UI');
    assert.match(await js("document.querySelector('#outcome').textContent"),/不等同于按游戏规则失败/);assert.equal(await js("document.querySelector('#act').disabled"),true);checks.push('benchmark interruption is visibly distinct from game loss and disables actions');
    assert.equal(await js("document.querySelector('#card-action-panel')"),null);assert.ok(await js("[...document.querySelectorAll('.card')].every(c=>c.disabled)"));checks.push('expired deadline disables confirmation and a changed observation clears stale card selection');
    const messages=await call(`/rollouts/${snapshot.room.episodeId}/messages?playerId=p1`);assert.ok(messages.messages.some(m=>m.kind==='tool-call'));checks.push('human runtime tool trajectory stored');
    const prohibited=await js("window.coopPlayer.command('audit').then(()=>false,()=>true)");assert.equal(prohibited,true);checks.push('player IPC cannot invoke audit');
    await js("window.coopPlayer.command('disconnect')");return {ok:true,backend:'mock',fixture:'Scripted HTTP responses exercise client behavior only; no game engine or scoring validation.',checks};
  }finally{await local.close();}
}
